### ISSUE TITLE
utils/dicts/__init__.py uses old-style relative imports

### ISSUE THREAD

**Issue by davclark** [haaksmash/pyutils#12]
lines like

    from limited_dict import LimitedDict

Should be changed to

    from .limited_dict import LimitedDict

I don't know if you care to support python >=2.5, so I wanted to ask you to make the change. But I'm happy to make a pull request. The PEP on this is here:

https://www.python.org/dev/peps/pep-0328/

(which is referenced here: https://docs.python.org/3/reference/simple_stmts.html#the-import-statement)

**Comment by haaksmash** [comment]
Dav, great catch --- that's definitely an oversight on my part! I'll get to this tonight, but feel free to submit a pull request if you don't want to wait that long :) If you do, would you mind turning off implicit relative imports everywhere as well? But like I said, I'll get this out tonight regardless.
