### ISSUE TITLE
Package "tests" is included in the distribution

### ISSUE THREAD

**Issue by anthrax-0** [haaksmash/pyutils#23]
PyPi version  1.0.0 of the "utils" includes also "tests" package which creates naming conflicts in many places. I suggest changing setup.py as described here (using "exclude"): https://setuptools.readthedocs.io/en/latest/setuptools.html#using-find-packages should help.

**Comment by haaksmash** [comment]
@anthrax-0 thanks for the report and helpful link!

Seems like you're thinking https://github.com/haaksmash/pyutils/blob/0c7d4874bbaf1730fb858902534ac76a84f26161/setup.py#L15 could become 

```python
packages=find_packages(exclude=[*.tests]),
```
? PRs are always welcome 😉

**Comment by haaksmash** [comment]
@anthrax-0 hopefully the new patch version solves the problem! Feel free to re-open this issue if not.

**Comment by anthrax-0** [comment]
I think in `pyutils` case exclude should look like this:
` packages=find_packages(exclude=["tests", "tests.*"]),`
