### ISSUE TITLE
Feature_Engineering

### ISSUE THREAD

**Issue by Bcopeland64** [haaksmash/pyutils#27]
Is the feature_engineering function no longer a part of this package?

**Comment by haaksmash** [comment]
Hi Brandon, sorry it's taken a while to answer your question. I believe you have this package confused with another one; `feature_engineering` has never been part of `pyutils`, which aims to be a relatively general set of helper methods for manipulating common data structures more ergonomically. "`feature_engineering`" sounds a little too specialized to be here!

in #26, we were able to figure out what was going on with a similar source of confusion; maybe you'll find that issue helpful?

Good luck on your journey to data science!
