### ISSUE TITLE
Folder "tests" back again in distribution

### ISSUE THREAD

**Issue by mahtin** [haaksmash/pyutils#28]
I see that issue #23 is closed; however, the `tests` folder is back!

This was found via the exact same bug being present in https://github.com/cloudflare/python-cloudflare package (now fixed). See https://github.com/cloudflare/python-cloudflare/issues/178#issuecomment-1877969754

I think the `find_packages()` call in `setup.py` is hiccuping.

**Comment by mahtin** [comment]
PR added!

**Comment by haaksmash** [comment]
Thank you, @mahtin! This is very much appreciated. I'll take a look at your PR today!

**Comment by mahtin** [comment]
@haaksmash - can you bump the version and push to pypi? https://pypi.org/project/pyutils/

**Comment by mahtin** [comment]
Thank you (ignore my late night major-typo). I see `1.0.2` pushed to https://pypi.org/project/utils/ now. Thank you.
