### ISSUE TITLE
'module 'utils' has no attribute 'generate_pyramid_anchors'

### ISSUE THREAD

**Issue by sip0724** [haaksmash/pyutils#31]
"Why does the error 'module 'utils' has no attribute 'generate_pyramid_anchors'' occur?
version==1.0.2

**Comment by haaksmash** [comment]
I think you've found yourself in the wrong repository, @sip0724; perhaps you meant to ask this question in https://github.com/matterport/Mask_RCNN?

As you can see in the git history, this package has never exposed a helper by that name. Good luck in your debugging!
